### ISSUE TITLE
Map zoom

### ISSUE THREAD

**Issue by brettaugust** [SEL-Columbia/dokomoforms#116]
Can't zoom in or out of map more than 1-2 levels before it disappears and freezes in worst case

**Comment by Snkz** [comment]
what device are you on?

**Comment by brettaugust** [comment]
windows laptop

--------
Brett Gleitsmann
bag2120@columbia.edu
347-392-9341

**Comment by vr2262** [comment]
And which browser?

**Comment by brettaugust** [comment]
chrome

--------
Brett Gleitsmann
bag2120@columbia.edu
347-392-9341
