### ISSUE TITLE
mobile submission fails on nigeria carrier

### ISSUE THREAD

**Issue by carbz** [SEL-Columbia/dokomoforms#143]
![screenshot_2015-05-26-19-33-42](https://cloud.githubusercontent.com/assets/1178209/7820208/c8ff4de4-03de-11e5-95ac-7ecbaeaacc48.png)
![Uploading Screenshot_2015-05-26-19-31-36.png…]()

**Comment by Snkz** [comment]
Try clearing your device storage by clicking the menu icon in the top right corner and clicking Clear all saved surveys.
![clear](https://cloud.githubusercontent.com/assets/788607/7820599/749f63aa-03b7-11e5-8749-53ec82c44fe9.png)
Submit again and let me know if it crashes.

**Comment by carbz** [comment]
Did so but now I'm getting stuck on the 'Save survey' page. Cannot even
submit.

Also, how does it know I'm incompetent and do I need an excuse?

-carbz

+234-81-7347-6284 [Nigeria cell]

**Comment by vr2262** [comment]
If you have to ask, your incompetence is clear. Yes, an explanation is required.

**Comment by carbz** [comment]
I got past that on another try but still failing in upload...

It could be my device but bandwidth is sufficient to send this email and
post to github. I'll try another phone at some point...

**Comment by carbz** [comment]
Fails on upload from another Nigerian cell carrier. Started fresh too.

**Comment by Snkz** [comment]
Hm,, thats not good ... Try doing a submission that contains no values for both the Date and Time questions. Clear all survey data again and refresh the page before doing so. Hopefully we can pinpoint the problem to a specific question type. Date and Time have been known to be problematic.

**Comment by Snkz** [comment]
i found what was causing the problem, all new submissions should go through without any hiccups now. If it works for you let me know and I'll close this issue

**Comment by carbz** [comment]
Works now. Nice display of competence.

+234-81-7347-6284 [Nigeria cell]
On May 27, 2015 5:04 PM, "Abdi Dahir" <notifications@github.com> wrote:

i found what was causing the problem, all new submissions should go through
without any hiccups now. If it works for you let me know and I'll close
this issue

—
Reply to this email directly or view it on GitHub
<https://github.com/SEL-Columbia/dokomoforms/issues/143#issuecomment-105977484>
.

**Comment by Snkz** [comment]
woot
