### ISSUE TITLE
Error on submission on 'location' question - revisit issue

### ISSUE THREAD

**Issue by brettaugust** [SEL-Columbia/dokomoforms#144]
Vijay and I were using it on his blackberry and he got it to give an error from the last question. I just recreated it now. On the last question which is about location, if you select one of the nearby locations, but then say create a new one, it gives an error:
![image](https://cloud.githubusercontent.com/assets/3341614/7848564/df2abdf8-049a-11e5-8cc7-b280a6d41969.png)

**Comment by brettaugust** [comment]
![image](https://cloud.githubusercontent.com/assets/3341614/7848581/1c1f5214-049b-11e5-8c0e-a6bd892f1cb2.png)

and then select, 'add new facility'.  a new page pops up 
![image](https://cloud.githubusercontent.com/assets/3341614/7848599/3e2aa1a6-049b-11e5-8270-0a2606c4a9c1.png)

and then if i click "next question" i get the error page

**Comment by Snkz** [comment]
The error messages are very none specific, we'll definitely change them before the next release however when adding a new facility, you must fill out all fields, including name and sector. Clicking on add new facility deselects any selected facility on the previous view.
