### ISSUE TITLE
Should we enforce that submissions include every question, even if skipped?

### ISSUE THREAD

**Issue by vr2262** [SEL-Columbia/dokomoforms#50]
Similar to #45 

At the moment, a submission JSON has an `answers` field, which is a list of dictionaries, and if any questions are not included in the list, it is assumed that they have been skipped. The other way to skip a question is for the `answer` value to be `null`.

Should we forbid skipping questions by leaving them out of the `answers` list? In other words, is this...

```
[<answer to question 1>, <answer to question 2>: null,<answer to question 3>]
```

preferable to this...

```
[<answer to question 1>, <answer to question 3>] # question 2 skipped
```

?

@csytan

**Comment by Snkz** [comment]
Currently filtering out null responses in front end.
